# Generated by Django 3.2 on 2023-01-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitid', models.FloatField(primary_key=True, serialize=False)),
                ('circuitref', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('alt', models.BigIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'circuits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructorid', models.FloatField()),
                ('constructorref', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'constructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverid', models.FloatField(primary_key=True, serialize=False)),
                ('driverref', models.CharField(blank=True, max_length=20, null=True)),
                ('forename', models.CharField(blank=True, max_length=20, null=True)),
                ('surname', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceid', models.FloatField(primary_key=True, serialize=False)),
                ('round', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('datetime_field', models.DateField(blank=True, db_column='datetime_', null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'races',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultid', models.FloatField(primary_key=True, serialize=False)),
                ('raceid', models.FloatField(blank=True, null=True)),
                ('constructorid', models.FloatField(blank=True, null=True)),
                ('num_car', models.FloatField(blank=True, null=True)),
                ('start_pos', models.BigIntegerField(blank=True, null=True)),
                ('final_pos', models.BigIntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, max_length=20, null=True)),
                ('positionorder', models.CharField(blank=True, max_length=20, null=True)),
                ('points', models.BigIntegerField(blank=True, null=True)),
                ('nbr_laps', models.BigIntegerField(blank=True, null=True)),
                ('time_total', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('num_fastestlap', models.FloatField(blank=True, null=True)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('fastestlaptime', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fastestlapspeed', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('statusid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'results',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'The Question', 'verbose_name_plural': 'Peoples Questions'},
        ),
    ]
